### ISSUE TITLE
Install issues on CentOS 8

### ISSUE THREAD

**Issue by douglasawh** [Faldrian/bandcamp-scraper#2]
I have not done much trouble-shooting on this, and I am not sure how much time I will have to devote to it, but I wanted to log the issue in case others hit it.

My guess is that the couchdb instructions at https://docs.couchdb.org/en/stable/install/index.html do not work on CentOS 8. I guess I should give it a go on CentOS 7...I'll report in the comments.

[centos@localhost bandcamp]$ scrapy crawl tags
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python3.6/site-packages/scrapy/cmdline.py", line 142, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "/usr/local/lib/python3.6/site-packages/scrapy/crawler.py", line 280, in __init__
    super(CrawlerProcess, self).__init__(settings)
  File "/usr/local/lib/python3.6/site-packages/scrapy/crawler.py", line 152, in __init__
    self.spider_loader = self._get_spider_loader(settings)
  File "/usr/local/lib/python3.6/site-packages/scrapy/crawler.py", line 146, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "/usr/local/lib/python3.6/site-packages/scrapy/spiderloader.py", line 60, in from_settings
    return cls(settings)
  File "/usr/local/lib/python3.6/site-packages/scrapy/spiderloader.py", line 24, in __init__
    self._load_all_spiders()
  File "/usr/local/lib/python3.6/site-packages/scrapy/spiderloader.py", line 46, in _load_all_spiders
    for module in walk_modules(name):
  File "/usr/local/lib/python3.6/site-packages/scrapy/utils/misc.py", line 77, in walk_modules
    submod = import_module(fullpath)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/centos/bandcamp-scraper/scraper/bandcamp/spiders/tags.py", line 5, in <module>
    import couchdb
ModuleNotFoundError: No module named 'couchdb'

[centos@localhost bandcamp]$ which couchdb
/usr/bin/which: no couchdb in (/home/centos/.local/bin:/home/centos/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)

[centos@localhost bandcamp]$ sudo yum install couchdb
Last metadata expiration check: 0:07:25 ago on Tue 19 May 2020 10:31:16 AM CDT.
Package couchdb-3.1.0-1.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

**Comment by Faldrian** [comment]
Ah, maybe you need to install a python package "couchdb" in addition, so you have an api that python can use. Maybe I forgot to include that instruction in my readme (but I don't know the package by heart, so I'll add it later or you do).

**Comment by douglasawh** [comment]
@Faldrian that seems to have done it! Thanks!

It looks like I have some sort of networking issue, but I probably just need to start the couchdb service or something. I'll report back the resolution in case others hit the issue.

[centos@localhost bandcamp]$ scrapy crawl tags
2020-05-19 10:48:35 [scrapy.utils.log] INFO: Scrapy 2.1.0 started (bot: bandcamp)
2020-05-19 10:48:35 [scrapy.utils.log] INFO: Versions: lxml 4.5.1.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 20.3.0, Python 3.6.8 (default, Nov 21 2019, 19:31:34) - [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)], pyOpenSSL 18.0.0 (OpenSSL 1.1.1c FIPS  28 May 2019), cryptography 2.3, Platform Linux-4.18.0-147.8.1.el8_1.x86_64-x86_64-with-centos-8.1.1911-Core
2020-05-19 10:48:35 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'bandcamp',
 'DEPTH_PRIORITY': 1,
 'LOG_LEVEL': 'INFO',
 'NEWSPIDER_MODULE': 'bandcamp.spiders',
 'SCHEDULER_DISK_QUEUE': 'scrapy.squeues.PickleFifoDiskQueue',
 'SCHEDULER_MEMORY_QUEUE': 'scrapy.squeues.FifoMemoryQueue',
 'SPIDER_MODULES': ['bandcamp.spiders']}
2020-05-19 10:48:35 [scrapy.extensions.telnet] INFO: Telnet Password: 4b9235951864e5a9
2020-05-19 10:48:35 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats']
2020-05-19 10:48:35 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2020-05-19 10:48:35 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2020-05-19 10:48:35 [scrapy.middleware] INFO: Enabled item pipelines:
['bandcamp.pipelines.BandcampPipeline']
2020-05-19 10:48:35 [scrapy.core.engine] INFO: Spider opened
2020-05-19 10:48:35 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2020-05-19 10:48:35 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2020-05-19 10:48:35 [scrapy.core.engine] ERROR: Error while obtaining start requests
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/scrapy/core/engine.py", line 129, in _next_request
    request = next(slot.start_requests)
  File "/home/centos/bandcamp-scraper/scraper/bandcamp/spiders/tags.py", line 26, in start_requests
    self.albumdb = couch.create('album')
  File "/usr/local/lib64/python3.6/site-packages/couchdb/client.py", line 221, in create
    self.resource.put_json(name)
  File "/usr/local/lib64/python3.6/site-packages/couchdb/http.py", line 578, in put_json
    **params)
  File "/usr/local/lib64/python3.6/site-packages/couchdb/http.py", line 596, in _request_json
    headers=headers, **params)
  File "/usr/local/lib64/python3.6/site-packages/couchdb/http.py", line 592, in _request
    credentials=self.credentials)
  File "/usr/local/lib64/python3.6/site-packages/couchdb/http.py", line 295, in request
    conn = self.connection_pool.get(url)
  File "/usr/local/lib64/python3.6/site-packages/couchdb/http.py", line 515, in get
    conn.connect()
  File "/usr/lib64/python3.6/http/client.py", line 946, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib64/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib64/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2020-05-19 10:48:35 [scrapy.core.engine] INFO: Closing spider (finished)
2020-05-19 10:48:35 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'elapsed_time_seconds': 0.046003,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2020, 5, 19, 15, 48, 35, 711311),
 'log_count/ERROR': 1,
 'log_count/INFO': 10,
 'memusage/max': 54677504,
 'memusage/startup': 54677504,
 'start_time': datetime.datetime(2020, 5, 19, 15, 48, 35, 665308)}
2020-05-19 10:48:35 [scrapy.core.engine] INFO: Spider closed (finished)

**Comment by douglasawh** [comment]
it turns out that setting a password is not optional in the packaged version of couchdb. Couch was saying it was running via ps, but it was in a state such that it wasn't listening. So, that's resolved, but I have a new issue to resolve.

Pretty sure the username and password needs to be set before this line, but I'm not sure how to do that. Once I figure it out, I will post so others can do so too.

  File "/home/centos/bandcamp-scraper/scraper/bandcamp/spiders/tags.py", line 26, in start_requests
    self.albumdb = couch.create('album')

**Comment by Faldrian** [comment]
Thanks for leaving the pull request giving another user some assistance how to install it properly. :)
